### ISSUE TITLE
DAB recipes to install Opendigitalradio and related tools

### ISSUE THREAD

**Issue by DavidLutton** [gnuradio/gr-recipes#53]
I have made [DAB recipes](https://github.com/DavidLutton/DAB-recipes) to install [Opendigitalradio](https://github.com/Opendigitalradio) and related tools with PyBOMBS.

Any recommendations for:
- Tiding towards PyBOMBS style
- Prerequisites for getting included with PyBOMBS recipes, Is this relevant to GNUradio?
- Licence for DAB recipes
- Package names for dependences on different operating systems
- Other aspects that I have not yet considered

**Comment by mbr0wn** [comment]
- Submit new recipes against https://github.com/gnuradio/gr-etcetera
- License: As long as you're not violating any laws, no requirements. PyBOMBS will download and install stuff all kinds of license.
- In gr-etcetera, we have a low bar for entry. If many people think this is stable and relevant, we move it to gr-recipes.
- You'll need to take a stab at figuring out package names for dependencies. However, don't fret if it only works well on a few distros. If someone tries to install on a less common OS, and it fails, they can submit an issue.
- Relevance to GNU Radio is subjective. That's why we have gr-etcetera.

Hope this is helpful!
